version: '3.7'

services:
  postgres:
    image: postgres:16
    container_name: mlflow_s3_db
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mlflow"]
      interval: 2s
      timeout: 5s
      retries: 10
    ports: # Expose for debugging if needed
      - "5435:5432"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.2
    container_name: mlflow_s3_server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # NOTE: MLFLOW_SERVER_ALLOWED_HOSTS is removed as it is not needed for v2.x
      
      # Use Chameleon S3 Endpoint
      MLFLOW_S3_ENDPOINT_URL: https://chi.tacc.chameleoncloud.org:7480
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
      
      # EC2 Credentials found via openstack CLI
      AWS_ACCESS_KEY_ID: 194452c2790b4b8d991c5ebba7b9aa38
      AWS_SECRET_ACCESS_KEY: 8b31bcd3474c41c4941fe2359664b17a
      
    ports:
      - "5010:5000"
    command: >
      /bin/sh -c "pip install psycopg2-binary boto3 &&
      mlflow server 
      --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow 
      --artifacts-destination s3://test-tracker-verification/mlflow-test/
      --serve-artifacts 
      --host 0.0.0.0 
      --port 5000
      --gunicorn-opts '--timeout 300'"
